# -*- coding: utf-8 -*-
# Generated by Django 1.9.9 on 2016-09-19 01:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('waffle', '0002_flag_accounts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flag',
            name='groups',
        ),
    ]
